In [2]:
import numpy as np

In [3]:
from time import process_time

time taken by list


In [4]:
python_list=[i for i in range(100000)]
start_time= process_time()
python_list=[i*5 for i in python_list]
end_time= process_time()
print(end_time-start_time)

0.013005750999999677


time taken by numpy array


In [5]:
numpy_array=np.array([i for i in range(100000)])
start_time =process_time()
numpy_array*=5
end_time=process_time()
print(end_time-start_time)

0.0005003029999999242


In [6]:
c=np.array([(1,2,3,),(4,6,7)],dtype=float)

In [7]:
print(c)

[[1. 2. 3.]
 [4. 6. 7.]]


In [8]:
y= np.zeros((4,5))
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
c=np.array([(1,2,3,)])

In [10]:
print(c)

[[1 2 3]]


In [11]:
c=np.array([(1,2,3,),(4,6,7)])

In [12]:
print(c)

[[1 2 3]
 [4 6 7]]


In [13]:
la=np.ones((2,10))

In [14]:
print(la)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
a=np.full((3,4),4)

In [16]:
print(a)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [17]:
a=np.eye(8)

In [18]:
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [19]:
a=np.random.random((4,5))

In [20]:
print(a)

[[0.34538569 0.36627737 0.59658725 0.96168259 0.00458696]
 [0.03663048 0.43144418 0.04080455 0.92246677 0.13919599]
 [0.9020309  0.1291318  0.56467524 0.50582384 0.95456512]
 [0.30761199 0.82943199 0.82584864 0.30407839 0.37645584]]


In [23]:
a=np.random.randint(10,15,(5,5))
print(a)

[[12 11 14 12 12]
 [10 12 11 13 11]
 [13 13 11 11 11]
 [12 10 11 12 14]
 [12 10 10 10 13]]


In [24]:
a=np.linspace(10,15,14)
print(a)

[10.         10.38461538 10.76923077 11.15384615 11.53846154 11.92307692
 12.30769231 12.69230769 13.07692308 13.46153846 13.84615385 14.23076923
 14.61538462 15.        ]


In [26]:
a=np.linspace(10,50,5)
print(a)

[10. 20. 30. 40. 50.]


In [29]:
a=np.arange(10,30,2)
print(a)

[10 12 14 16 18 20 22 24 26 28]


In [30]:
list=[1,2,3,4,5,6,7,8]
np_array=np.asarray(list)
print(list)
print(np_array)

[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]


In [32]:
c=np.random.random((4,8))
print(c)

[[0.05509607 0.61310444 0.82467759 0.80200722 0.32845681 0.3435437
  0.89112433 0.6633726 ]
 [0.6313325  0.71981415 0.236912   0.32024578 0.87730859 0.16062446
  0.5180538  0.86789521]
 [0.44981394 0.07746169 0.33974673 0.99861166 0.55804784 0.3547289
  0.21566695 0.52686957]
 [0.15820694 0.7800475  0.23322427 0.28233455 0.54923569 0.84590678
  0.57435613 0.50351784]]


In [35]:
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)

(4, 8)
2
32
float64


mathematical operation of a numpy array


In [36]:
list_1=[1,2,3,4,5,6,"ijk"]
list_2=[4,7,"f",9]
print(list_1+list_2)

[1, 2, 3, 4, 5, 6, 'ijk', 4, 7, 'f', 9]


In [46]:
a=np.random.randint(10,20,(3,5))
b=np.random.randint(30,60,(3,5))
print(a)
print(b)

[[18 19 12 19 17]
 [17 12 13 11 17]
 [15 19 18 12 19]]
[[37 36 57 51 54]
 [58 34 55 32 45]
 [48 58 59 53 32]]


In [47]:
print(a+b)
print(a*b)

[[55 55 69 70 71]
 [75 46 68 43 62]
 [63 77 77 65 51]]
[[ 666  684  684  969  918]
 [ 986  408  715  352  765]
 [ 720 1102 1062  636  608]]


In [39]:
a= np.array([1,2,3,4,"d"])
print(a)

['1' '2' '3' '4' 'd']


In [43]:
a= np.array([1,2,3,4])
b= np.array([1,2,3,4])
print(a+b)

[2 4 6 8]


In [49]:
a=np.random.randint(10,20,(4,5))
b=np.random.randint(30,60,(4,5))
print(a)
print(b)
print(a*b)

[[11 17 18 16 19]
 [10 14 12 18 10]
 [13 14 19 15 17]
 [19 15 14 19 17]]
[[33 48 47 35 31]
 [46 30 46 43 59]
 [46 40 33 32 51]
 [54 30 46 54 48]]
[[ 363  816  846  560  589]
 [ 460  420  552  774  590]
 [ 598  560  627  480  867]
 [1026  450  644 1026  816]]


In [52]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[44 65 65 51 50]
 [56 44 58 61 69]
 [59 54 52 47 68]
 [73 45 60 73 65]]
[[-22 -31 -29 -19 -12]
 [-36 -16 -34 -25 -49]
 [-33 -26 -14 -17 -34]
 [-35 -15 -32 -35 -31]]
[[ 363  816  846  560  589]
 [ 460  420  552  774  590]
 [ 598  560  627  480  867]
 [1026  450  644 1026  816]]
[[0.33333333 0.35416667 0.38297872 0.45714286 0.61290323]
 [0.2173913  0.46666667 0.26086957 0.41860465 0.16949153]
 [0.2826087  0.35       0.57575758 0.46875    0.33333333]
 [0.35185185 0.5        0.30434783 0.35185185 0.35416667]]


In [53]:
array=np.random.randint(10,50,(6,7))
print(array)


[[26 39 41 43 34 44 31]
 [25 17 29 14 15 13 16]
 [11 48 18 32 28 43 15]
 [15 22 45 47 38 30 13]
 [20 37 38 45 29 25 13]
 [19 29 29 35 34 16 28]]


In [54]:
trans=np.transpose(array)

In [55]:
print(trans)

[[26 25 11 15 20 19]
 [39 17 48 22 37 29]
 [41 29 18 45 38 29]
 [43 14 32 47 45 35]
 [34 15 28 38 29 34]
 [44 13 43 30 25 16]
 [31 16 15 13 13 28]]


In [56]:
trans_2=array.T
print(trans)

[[26 25 11 15 20 19]
 [39 17 48 22 37 29]
 [41 29 18 45 38 29]
 [43 14 32 47 45 35]
 [34 15 28 38 29 34]
 [44 13 43 30 25 16]
 [31 16 15 13 13 28]]


In [58]:
a=np.random.randint(1,10,(2,4))
print(a)
b=a.reshape(4,2)
print(b)

[[6 6 8 9]
 [8 8 2 5]]
[[6 6]
 [8 9]
 [8 8]
 [2 5]]
